### ISSUE TITLE
Remove the parking space between hobbies and qualifications

### ISSUE THREAD

**Issue by RyanRussell00** [HowellBen97/Portfolio_code#24]
![image](https://user-images.githubusercontent.com/35180491/92331348-c9040d00-f02a-11ea-84ee-ee7c8ae973a2.png)

**Comment by HowellBen97** [comment]
i don't see that issue anymore, and i havent changed anything
![Capture](https://user-images.githubusercontent.com/64659427/93018749-dc365000-f5c9-11ea-911a-8ce939bab77e.PNG)

**Comment by RyanRussell00** [comment]
- Move the hobbies into their own div
- Give the new hobbies div: `top: 100%` and 'position: inherit`
- Debug this on all browser sizes
